name: Build and Upload Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish as single-file self-contained executable
        run: |
          dotnet publish BAVirtual.Gibraltar/BAVirtual.Gibraltar.csproj -c Release -r win-x64 --self-contained true \
            -p:PublishSingleFile=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -p:EnableCompressionInSingleFile=true \
            -p:TrimUnusedDependencies=true \
            -p:DebugType=None \
            -p:DebugSymbols=false \
            -o output/${{ github.ref_name }}

      - name: Upload .exe to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/${{ github.ref_name }}/BAVirtual.Gibraltar.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}